#define tPLUS 0
#define tNOMBRE 1
#define tMOINS 1
#define tFOIS 2
#define tDIVISE 3
#define tPUISSANCE 4
#define tOP 5
#define tCP 6
#define tNEW_LINE 7 
#define tCOMPARAISON 8
#define tEGAL 9
#define tINFSTRICT 10
#define tSUPSTRICT 11
#define tSUPEGAL 12
#define tINFEGAL 13
#define tDIFF 14
#define tVIRG 15
#define tMAIN 16
#define tCONST 17
#define tVAR 18
#define tINT 19
#define tOB 20
#define tCB 21
#define tCHAR 22
#define tINT 23
#define tVAR 24

/*#define YYSTYPE int;
extern YYSTYPE yyval*/
